# "/" + 仓库的名字. 资源文件的路径组成部分
baseurl: "/my-first-web"

# 网页的标题
title: "强棒少女的陪伴日记"
username: yourname
# 网站副标题
description: "社一子伍"

aboutme: "社一子伍 腼腆的虎牙小妹"

# 其它配置, 可忽略, 无需修改
markdown: kramdown
gems: [jekyll-paginate]
paginate: 3
permalink: /:title/
paginate_path: "/page:num/"
